### ISSUE TITLE
Add information or FAQ on criteria and guidelines

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#153]
More information about how to make a Submission,  could be provided in a template submission page. 

The relation among taxonomy elements such as "Methods", "Tags" and "Tasks" and other common questions could be collected in a FAQ page.

**Comment by nathanshammah** [comment]
This is the link with the currently proposed [Metriq User Guidelines](https://docs.google.com/document/d/14yGVM0ZOoqrKhRJCsMM0lkHPAW8OWUYa1iE1vnkAcdk/edit?usp=sharing). @WrathfulSpatula @vprusso my suggestion is to add them to to website sooner rather than later and eventually iterate on the content as we improve it. 

One place I suggest adding them is in the About page or as a new Guidelines or Contributing page under the About tab in the top menu. Later on we can also include them in the wiki, but since the About page is one of the pages that a visitor first hits, they can be very helpful there.

**Comment by WrathfulSpatula** [comment]
Thank you, Nathan! For the moment, I don't seem any harm in duplicating the "About" tab information in its original home and also in the wiki, and it's probably slightly lower click depth or demand on user attention to have this information accessible in the "About" tab.

@vprusso, this might be a good issue for you to grab, but I can do this tomorrow, if I see you haven't assigned yourself.

**Comment by vprusso** [comment]
Closing this as this task was completed in https://github.com/unitaryfund/metriq-app/pull/525
