### ISSUE TITLE
Highlight current page in top right menu

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#155]
I would highlight current page one is looking at in the top right menu, similarly to we do on the [unitary.fund](https://unitary.fund) website. This could be a highlight background or a bolder font for the given category, like "**Tasks**" if one is looking at the Tasks page. Right now if one looks at the menu, does not see immediately the information of which page one is on.

**Comment by WrathfulSpatula** [comment]
@vprusso Is welcome to tackle this in the milestone in which you've placed it, unless he objects. My original hesitation was that we should probably find a way to do this with `react-router` and `react-bootstrap`, where it might _not_ be recommended according to those packages' best practices. However, if there's an easy-enough way to do this, particularly after `react-router` refactoring we did to improve back-button navigation, then Vincent can give it a shot.
