### ISSUE TITLE
Consider integration with the NISQ newsletter

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#157]
The NISQ newsletter is operated by USRA / NASA, https://riacs.usra.edu/quantum/nisqc-nl
It shares information on latest papers in NISQ. It also has a suggested submission page, https://riacs.usra.edu/quantum/nisqc-nl#suggest with classifiers and tags.

The integration could be at the level of API or at level of App. Some ideas for Metriq:
- It could look for elements in that database. 
- It could use their same classifiers.
- It could contact the folks running USRA and advertise Metriq there. Happy to help there.  

Also, on a higher level, the GUI and submission characteristics of the newsletter could be looked at, to  see if this can help inspire UI for Metriq.

**Comment by nathanshammah** [comment]
It would be great to enable an automatic summary of the recent submissions, and see if the NISQC-NL or SQMS digest want to include them as a section in their digest.

**Comment by nathanshammah** [comment]
Follow up from recent discussion with the USRA team: the path forward is to provide a reference API in `metriq-api` for submissions related to arXiv papers, so that the NISQ newsletter can look up which one are in Metriq, and provide a link to them.

**Comment by WrathfulSpatula** [comment]
@nathanshammah Per #498, the `arxiv_id` id route has been added and published.

For example: https://metriq.info/api/v1/arxiv_id/2201.11046

**Comment by nathanshammah** [comment]
Great! I am waiting for the first NISQ newsletter to be published with an example and then let's close this.
