### ISSUE TITLE
As a member, I want to add a submission URL as either an arXiv or GitHub link and have the title and description auto-populate.

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#167]
### Task:

If an arXiv or GitHub link is provided via the submission page, we should automatically scrape the title and description from their respective APIs. 

### User Story (User <-> System (Web app))

<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">User</th>
    <th class="tg-0pky">System (Web app)</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">1. (Authenticated user on `AddSubmission/` view)</td>
    <td class="tg-0pky">1. (Displaying "add submission" page)</td>
  </tr>
  <tr>
    <td class="tg-0pky">2. User puts a link in "Content URL" textbox with `https://arxiv.org/` prefix <b>OR</b> with `https://github.com/` prefix. </td>
    <td class="tg-0pky">2.</td>
  </tr>
  <tr>
    <td class="tg-0pky">3. </td>
    <td class="tg-0pky">3. Content in "Submission Name" and "Description" text boxes auto-populate. </td>
  </tr>
  <tr>
    <td class="tg-0lax">4. User deletes the content in the "Content URL" textbox.</td>
    <td class="tg-0lax">4.</td>
  </tr>
  <tr>
    <td class="tg-0lax">5.</td>
    <td class="tg-0lax">5. Any text that was dynamically populated from step <b>3.</b> is removed from both "Submission Name" and "Description". </td>
  </tr>
  <tr>
    <td class="tg-0lax">6. <i>(Successful call)</i> </td>
    <td class="tg-0lax">6. <i>(Successful response)</i></td>
  </tr>
</tbody>
</table>

Here are the relevant links for the GitHub and arXiv REST APIs, respectively:

- [GitHub REST API](https://docs.github.com/en/rest)
- [arXiv REST API](https://arxiv.org/help/api)

**Comment by cometta** [comment]
PR : 

https://github.com/unitaryfund/metriq-api/pull/193
https://github.com/unitaryfund/metriq-app/pull/590

**Comment by nathanshammah** [comment]
Thanks @cometta!

**Comment by WrathfulSpatula** [comment]
Thanks @cometta!
