### ISSUE TITLE
As a member, I would like to be able to track and display the submissions I perform on metriq

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#172]
### Task

This task as it currently stands is a placeholder, but the idea here would be to include a way to display the number of submissions held by a given registered member of the metriq platform. This could be used as a form of reputation in a similar manner in which sites like StackOverflow, Wikipedia, etc. utilize the same criteria.

**Comment by WrathfulSpatula** [comment]
Partly, this was addressed by the option to click a user name, when it occurs on a submission, and to see a filtered list of the user's submissions. We need a user profile page for editing affiliation and other details, now. Since #188 is closed, we'll track the progress here in this issue.

**Comment by WrathfulSpatula** [comment]
Reading the issue (and title) again, I think we've addressed this. User name is displayed in submission summary boxes, and clicking it takes one to a list of all submissions by that user. I think we can close this.
