### ISSUE TITLE
As a user, I want to use the metriq platform for domains in quantum information outside of benchmarking, so that I can use the metriq structure for other problems

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#176]
Possibly related: https://github.com/unitaryfund/metriq-app/issues/186

**Comment by WrathfulSpatula** [comment]
I recognize this issue as the statement of a user story, from very early in the development process, but, by now, I think Metriq has demonstrated its flexibility in accommodating data besides "results." I think that's sufficient, to consider this user story to be addressed.
