### ISSUE TITLE
Add secondary alphabetical sorting

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#254]
In the Popular leaderboard, currently the primary sorting of tasks, methods and tags is by upvotes. I am not sure of the secondary sorting, I imagine chronological order. I propose to use alphabetical order as secondary sorting, i.e., to order items with the equal amount of upvotes.

**Comment by WrathfulSpatula** [comment]
The sort is otherwise "unstable," so this would remove that ambiguity. Let's go ahead with it.
