### ISSUE TITLE
Add State-of-the-Art page

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/metriq-app#258]
Papers with code offers a page that has the best in class submitted to the platform for different tasks. Does it make sense to have something similar, could be a good way to motivate folks to make submissions :)

**Comment by nathanshammah** [comment]
Practically, I propose to showcase those charts where SOTA can be discerned from other results. This implies showing  charts that contain many results. These are hard to find right now, as we count submissions, but these are not enough to generate a chart (we need 3+ numerical results against the same metric to generate a chart). Practically, keeping track of total results in a chart of a given metric beyond a given threshold could be used to decide whether they make it to the SOTA. 

To begin with, if it's a bit too much work to count or generate such counters, here is a list of well populated charts that could be added to the page manually, before implementing an automation:

- 1. Hardware: [Quantum Volume](https://metriq.info/Task/34)
- 2 Compilers: [Circuit depth](https://metriq.info/Task/25), for t|ket⟩ benchmark circuit ex1_226.qasm
- 3. [Gate count](https://metriq.info/Task/25), for t|ket⟩ benchmark circuit ex1_226.qasm
- 4. Applications: [Approx ratio for MAXCUT](https://metriq.info/Task/1)
- 5. Applications: [Integer factoring](https://metriq.info/Task/4)
- 6. Applications: [Search - Hellinger distance](https://metriq.info/Task/23) 
- 7. Hardware: [T2](https://metriq.info/Task/50)

How does that sound? @WrathfulSpatula @willzeng @crazy4pi314 @vprusso?

**Comment by crazy4pi314** [comment]
So I think the inspiration for this issue was basically this page on paperswithcode.com: https://paperswithcode.com/sota

This has sections for each task, then has cards for each task that link to an [overview page](https://paperswithcode.com/task/semantic-segmentation) for that method which lists a leaderboard for results for that method and task. This is harder in our case because there isn't a unique benchmark or metric for a particular task/method combo.

I think for your suggestion of the hardcoded ones, I am wary of just picking charts/data to show on a sota page. I think your initial idea of filtering task/method/metric combos that have 3+ results and showing a link to the page with the plot/table would be a good solution (time depending).

**Comment by nathanshammah** [comment]
Similarly to papers with code, I was suggesting just collating the links that take folks to the proper charts in the usual pages. They could be cards similar to the [Tasks](https://metriq.info/Tasks) top level right now, with some data (submissions, likes, results). 

Basic mock-up below:

<img width="766" alt="Screen Shot 2022-03-15 at 17 47 03" src="https://user-images.githubusercontent.com/14573436/158429153-95a68f8b-840c-439c-bc2a-0c1441249193.png">


Sounds good to have the filtering based on results.

**Comment by WrathfulSpatula** [comment]
Following Nathan's mock-up, after discussing it with him earlier today, the tasks index and detail views basically already _do_ directly show SOTA on a given task. However, users clicking through the task hierarchy have no good idea of what is below, in child tasks. With #500, we add result count to the task index view and child tasks in the task detail view. Hopefully, this addresses the intent.
