### ISSUE TITLE
Add more support text to the submission page

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/metriq-app#267]
Would be helpful to communicate more detailed information about how to submit things that exceeds the scope of tooltips. Then we have more space for text and diagrams to help communicate to users how submission works.

Also adding at the top of the page breifly expectations for who we want to submit thing to empower users to submit thinks. Paperswithcode has this:

> If you are a researcher, you can can add pages for your own methods to make them more easily discoverable by the community, bringing more attention to your work.
>
>If you are part of the wider community, you can help by adding methods to the corpus so others can keep-up-to-date with deep learning developments. It is also a great way to learn!

**Comment by WrathfulSpatula** [comment]
@crazy4pi314 I did add a paraphrasing of the above two sentences to the submission page, but please reopen the issue, if this didn't fully address the need.
