### ISSUE TITLE
Send link once submission approved

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#332]
Send an email with the link to the published page once the submission is approved, to inform the contributor. It could say something like:

Thanks for contributing to Metriq! You submission is now live at [URL]. You can share the metriq with the community and keep track of it on [metriq.info](metriq.info).

**Comment by willzeng** [comment]
Is it not possible for there to be a terminal script that marks approval and sends the email? There's not a need for a front end for this?

**Comment by vprusso** [comment]
Nice catch, @nathanshammah. I'll look into this one.

**Comment by vprusso** [comment]
Closes in https://github.com/unitaryfund/metriq-api/pull/180

@WrathfulSpatula
