### ISSUE TITLE
"Trending" order might be reversed

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#341]
I added a vm6502q/qrack submission to the production environment, today, and I upvoted it. It is now bottom of the list, for "Trending" sort. This seems exactly reversed. Investigate and fix if necessary, please. (This likely needs a SQL query update, in the back end API repository.)

**Comment by WrathfulSpatula** [comment]
The submission in question is now first on the "Trending" list. I think the issue was that my timestamps were off and produced a negative upvotes-per-time statistic. So long as we use built-in functions for setting a current date/time stamp, like on submission approval, I think this was a false positive.

**Comment by WrathfulSpatula** [comment]
There's an integer casting precision problem, here. I have the actual fix for it.

**Comment by WrathfulSpatula** [comment]
@vprusso Sorry that went in `main`! That was the fix, though.

**Comment by vprusso** [comment]
No worries, nice catch with the fix!
