### ISSUE TITLE
First sentence preview cutoff misses a case.

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#342]
See [Application-Oriented Performance Benchmarks for Quantum Computing](https://metriq.info/Submission/14), but on the homepage. In the homepage preview, the description doesn't seem to stop at the end of the first sentence, as intended. Please investigate and fix the edge case.

**Comment by vprusso** [comment]
I think there might be two things happening here. It looks like in `SubmissionBox.js` it seems like this line:

```javascript
      description: !this.props.item.description ? '' : ((this.props.item.description.length > 500) ? (this.props.item.description.substring(0, 497) + '...') : this.props.item.description)
```

truncates it to 500, but then there is also code further down that cuts out the first sentence. 

```javascript
                {this.state.description ? this.state.description.split('. ')[0] + '.' : <i>(No description provided.)</i>}
```

At the very least, this is probably redundant, truncation should only be done once. At worst, maybe it's the culprit?

**Comment by WrathfulSpatula** [comment]
I think we want both checks, to produce the shorter of the two: stop at the first sentence break unless the "first sentence" is over 500 characters, (with ellipsis inserted).  We have to assume in web development that users _will_ engage _all_ edge cases in UI, basically. You could investigate further and fix this, or it'll be in my queue after #338, including a user story, first. (Thank you!)

**Comment by WrathfulSpatula** [comment]
By the way, don't rule out unexpected encoding in the string itself, in the database entry. There are potentially many ways to encode a `". "` sequence, to human eye. I actually _did_ have to deploy the PostgreSQL database with a slightly different encoding from QA, but, if that's the issue, this still can and should be solved in the front end, within reasonable expectation.

**Comment by vprusso** [comment]
I'm curious here what is causing the edge case. On my own local host of metriq, I attempted to upload the exact same entry, but it truncates in the appropriate place. So, I'm not sure what could be causing this problem.

**Comment by WrathfulSpatula** [comment]
Like I was trying to say, the encoding might be different, such that `". "` contains something like an extra null character that isn't preserved round-trip, just hypothetically.
