### ISSUE TITLE
Link to terms leads to 404

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#345]
When trying to register a new account on https://metriq.info/Register
![image](https://user-images.githubusercontent.com/5214594/143783332-669c82f8-3664-4730-b803-a9169005b48a.png)
 
Clicking the link to terms leads to a 404 page: https://metriq.info/MetriqTermsofUse.html

**Comment by WrathfulSpatula** [comment]
I found and fixed this on Wednesday, Will. You might be caching a redirect.

Have you tried hard-refreshing the page? (Ctrl+Shift+R)

**Comment by WrathfulSpatula** [comment]
@willzeng Nevermind. I was the one caching the page, not you. I had to test this in the production environment itself, so the fix is already up. I'm opening a PR, for Monday.

**Comment by willzeng** [comment]
Great!
