### ISSUE TITLE
Change website link to metriq-app

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#354]
Question: what if we change link on website in the top right of the header / menu to point one to the `metriq-app` repo, instead of `metriq-api`? Mainly because most issues of the front-end are opened and discussed there already.

I noticed it today when it was mentioned that users can open issues, and the presenter clicked on the link from the website in one of the demo, and it took one to the metriq-api repo, which has much less activity in terms of issues and discussions. I understand that technically metriq-api is containing all the pieces, but I think that we'd like to funnel usability and content-related issues to metriq app.

**Comment by vprusso** [comment]
Hmm, I think we do in fact want `metriq-api`. The `metriq-api` contains both `metriq-app` and `metriq-postges` as Git submodules, whereas just the `metriq-app` is only the `metriq-app`.

**Comment by nathanshammah** [comment]
I see this point, but I still think that the main issue raised above is more important, i.e., directing users to a repo with more activity and more discussion in terms of issues. In terms of numbers, I expect much less users interested in replicating the working mechanism of the web-app vs. those who may give general feedback on the website.

We could provide links to the other repos more prominently in the metriq-app repo readme.

**Comment by WrathfulSpatula** [comment]
I see both points, @vprusso and @nathanshammah. In the ideal, I'd prefer to agree with Vincent for myself, but in likely practice, I think Nathan is right. I'm going ahead with replacing this.
