### ISSUE TITLE
Enable a tidier taxonomy

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#363]
Currently, going to the "A Verified Optimizer for Quantum Circuits"page, one finds the following as [Methods](https://metriq.info/Submission/26):
<img width="199" alt="metriq-methods" src="https://user-images.githubusercontent.com/14573436/146916980-6c118071-96b2-431f-b9dc-55a7c98a9d31.png">
I see a couple of issues with the current list, as it is inhomogeneous. Moderators can act to tidy that up, I just think that this may happen again in the future so my question tries to abstract this a bit and ask: how can we enable a tidier taxonomy in general?
To begin with, I propose to add more contextual information on a good nomenclature and examples for "methods" and "tasks" in the methods and task root pages, possibly with (a link to) more information also in the FAQ page.

**Comment by vprusso** [comment]
I agree, I think something a bit more rigid would be useful. 

Another related thing that might be worthwhile is to borrow from the "submission" page of PWC:
https://paperswithcode.com/contribute/dataset/new 

(note, you'll need to be logged into PWC to see the above).

Issues are also related to that:

https://github.com/unitaryfund/metriq-app/issues/153
https://github.com/unitaryfund/metriq-app/issues/265

**Comment by WrathfulSpatula** [comment]
I discouraged the suggestion, originally, but I think a method hierarchy might also help, akin to tasks.

**Comment by WrathfulSpatula** [comment]
We _do_ have a method hierarchy, now. If there's more to be said on this issue, please reopen it.
