### ISSUE TITLE
Homepage re-skin: Social media and social credit elements

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#368]
The social media and social credit elements of Kass' redesign of the homepage require back end changes. Progress will be tracked in this issue ticket.

**Comment by willzeng** [comment]
Super glad to see this one in by the way. Social credit for submission is a great engagement feature :)

**Comment by nathanshammah** [comment]
Is this issue addressed by the current Submission page? Or what it meant here was to include a link to the submitter social media profiles? If I click on the submitter's name I get to a page with all their submission.

**Comment by nathanshammah** [comment]
#762 addresses this, so closing the issue and the milestone.
