### ISSUE TITLE
Unable to make submission

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#373]
When making a submission, upon first clicking submission button the message, "*Could not reach server." 

Then it now reads:

<img width="909" alt="Screen Shot 2022-01-12 at 18 40 57" src="https://user-images.githubusercontent.com/14573436/149193684-2ebd703d-9425-46f1-b290-d73c83c114ad.png">

**Comment by crazy4pi314** [comment]
I have the same thing, I got "could not reach server" once before getting the Bad request @nathanshammah got before: 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/6486256/149194050-8725d7fc-1aa2-4b71-bd8d-39610f329b87.png">

**Comment by WrathfulSpatula** [comment]
This is super helpful from both parties as a bug report, by the way. I'm on it, immediate top priority.

**Comment by WrathfulSpatula** [comment]
It was a configuration issue that has been fixed. Thanks for the helpful reports!
