### ISSUE TITLE
Deleted method not removed from task 

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#375]
Deleting a method of a result and of a submission does not remove it from the related task page. 

As an example, see https://metriq.info/Task/34, for Quantum volume, where I updated the method of two submissions  and relative results, removing "Quantum volume" from the methods (https://metriq.info/Submission/41 and https://metriq.info/Submission/43). "Quantum volume" is still listed as a method for both submissions and results, see snapshot below: 

**Plot**
<img width="1089" alt="Screen Shot 2022-01-15 at 19 48 50" src="https://user-images.githubusercontent.com/14573436/149634381-464bea01-b4ac-4d3a-9d1e-9c4efc4f4349.png">

**Table**
<img width="1121" alt="Screen Shot 2022-01-15 at 19 50 19" src="https://user-images.githubusercontent.com/14573436/149634377-e2732b0c-5da3-4a09-8cb2-bcdb11dc6c51.png">

**Comment by WrathfulSpatula** [comment]
Upon investigation, it looks like we fixed this issue last week, so I'm closing the ticket.
