### ISSUE TITLE
Suggest existing tags also after first unknown tag

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#377]
In a new submission (and later on also to a submission or to a result), one can add tags. Tags are suggested. Multiple tags can be inserted divided by commas. If the user chooses as first tag a tag that does not exist, then the database does not suggest any other tag if the user uses as subsequent tag an existing tag. 

It would be preferable if the system searched tags and suggested them for each tag separated by a comma, not just for the first one.

**Comment by WrathfulSpatula** [comment]
This will be addressed per #600.
