### ISSUE TITLE
Duplicate method

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#383]
Duplicate method for `ibmq-tokyo`. Besides removing the method with no attached data, it would be useful to understand how the duplicate came to be. 

See for reference https://metriq.info/Methods/ (snapshot below) and https://metriq.info/Method/24, https://metriq.info/Method/25.

<img width="392" alt="method-duplicate" src="https://user-images.githubusercontent.com/14573436/149781588-ab803478-c8c9-40d9-b891-c849d592bf99.png">

**Comment by vprusso** [comment]
Related: https://github.com/unitaryfund/metriq-app/issues/382

**Comment by WrathfulSpatula** [comment]
The duplicate has been deleted. Looking at the database rows, these two were created within seconds of each other, so I suspect a cause like maybe a race condition on a hard page refresh with a POST call. I can make sure that the task names are unique in the database, and then this can only happen again if names just _look_ the same, but differ in encoding or characters that are hard for the human eye to distinguish.
