### ISSUE TITLE
Submissions under review already listed

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#384]
Submissions that I currently have submitted and are still flagged as "under review" under the "My Submissions" page, show up in some parts of the website (but not in others).

<img width="1143" alt="Screen Shot 2022-01-18 at 15 27 51" src="https://user-images.githubusercontent.com/14573436/149956733-97a29683-8d0a-4046-88e6-1e883cc679c7.png">

Visible:
- on the submission page, see, e.g., https://metriq.info/Submission/46.
- under a Task, see, e.g., https://metriq.info/Task/34

Not visible:
- on the homepage if I click on "latest".

**Comment by WrathfulSpatula** [comment]
Not-yet-approved submissions are now not included in method/task/tag views.

We could restrict privileges to see by-index submission detail views, but do we need to do so? No one is going to browse into a submission via clicking a link, this way. _Not_ restricting the by-index detail view lets users immediately share their submission with a private audience, but not in the homepage and not in SOTA charts. I don't see a particular problem with that, and it might be fine to leave that part as-is. Yes, thumbnail and submission URL links could be malicious, but the submitter would have to personally publicize the detail view, (or via a personal proxy, I guess,) in order for anyone to be exposed.

(Please do re-open the issue, if anyone disagrees.)
