### ISSUE TITLE
Improve readability of title

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#387]
Improve the readability of the title and subtitle, "Community-driven Quantum Benchmarks // Submissions show performance of methods against tasks". Especially on Chrome from Mac there is insufficient contrast and it is quite hard to read as the font and size are thin with the chosen colors white/light blue.

Also, they have non sequential heading structure, ``<h2> and <h4>``.

**Comment by WrathfulSpatula** [comment]
Maybe we can use a bold weight font. I'll see how it looks on Ubuntu/Firefox, as well.

**Comment by WrathfulSpatula** [comment]
With that in, when I publish the release, please let me know if we can consider the issue resolved. I don't have Mac or iPhone access, but I suspect that bold weight font greatly helps.

**Comment by WrathfulSpatula** [comment]
Using Courier New might always lead to such differences between browsers and OS choices, so let's just use Arial, which is used elsewhere in the app.

**Comment by nathanshammah** [comment]
Thanks @WrathfulSpatula, this seems addressed to me, see below (desktop):

<img width="1393" alt="Screen Shot 2022-02-14 at 13 26 01" src="https://user-images.githubusercontent.com/14573436/153865035-36909dd2-b2d0-404b-bd0b-ec1ebdf690ca.png">

By the way, in Chrome you can emulate some mobile views including the iPhone, with View>Developer>Dev Tools. Maybe that helps in the future.
