### ISSUE TITLE
Autogenerate newsletter emails with "top" submissions

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/metriq-app#392]
See here: https://paperswithcode.com/newsletter

You can sign up for it looks like bi-weekly emails, with an archive available on the page. This could be helpful in generating more visits with these reminders of what is going on on Metriq.

**Comment by WrathfulSpatula** [comment]
We did this! Closing. :smile:

**Comment by WrathfulSpatula** [comment]
Rather, we allow users to self-curate, and we do it for new submissions, but these nonetheless seem to address the original intent.
