### ISSUE TITLE
Top-level topics

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#411]
Create top-level topics for submissions, with UI.

**Comment by nathanshammah** [comment]
Great.

**Comment by WrathfulSpatula** [comment]
After discussions with Nathan last week, the demanded feature seems to be for top-level _tasks_, at least. Since tasks are already hierarchical, we'll update the task index view to show the highest level topics, and users will have the option of clicking to see either the top-level task detail or child tasks, successively. (We'll track progress here in this issue.)

Since task detail views already list child tasks, the actionable content of this issue becomes to restrict the task index view to display _only_ top level tasks. This is trivial. We can also do the same with methods, if we add a method hierarchy.

**Comment by WrathfulSpatula** [comment]
@nathanshammah @willzeng Do we have particular top level topics in mind, for tasks? Most of the work here seems to be to decide what these top level categories actually are, and to update the database to reflect that decision. (I have a PR up already that restricts the tasks index view to top level categories, but the de facto categories are ad hoc, right now.)

**Comment by willzeng** [comment]
The topics you had drafted were great! Applications, Compilation, Hardware
and Simulators.

Worth keeping in mind in design that we may want to edit, remove, and
extend them later.

**Comment by nathanshammah** [comment]
Looks fine to me, thanks!

**Comment by nathanshammah** [comment]
By the way, next to tasks, I see use also for top-level categories for **Methods** to help with a tidier taxonomy #363 and sort out questions like the one here #435. For example, top-level methods could be:
"Superconducting-circuit processors">Rigetti80Q,H1, etc. 
"Neutral-atom processors">"Cs", etc. 
"Trapped-ion processors">"Yb+","Ca+", etc.

**Comment by WrathfulSpatula** [comment]
I'm collecting notes on the general topic of taxonomy and data model reorganization here, as we've gathered the related issues and seek to address them this week:

@crazy4pi314  raised the point in the submission party today that our data model seems to put the task of visualization first and work backwards to a schema. While this lets us visualize data easily, it puts a lot of load on the user, and it centers the visualization rather than the domain-specific knowledge in our data model. For example, for the t|ket> submission, hardware architecture becomes a permutation of a child task for a parent circuit definition task. We see almost the same thing happen with [Quantum Search on Noisy Intermediate-Scale Devices](https://arxiv.org/pdf/2202.00122.pdf), where hardware is permuted as sub-tasks, which is counterintuitive to domain experts.

While we might actually permute these out as tasks in our back end and database, it makes more sense, in terms of domain logic, to specify a single task, like the t|ket> circuit to compile. Then, as metadata on the **result**, the user has the option of selecting one hardware architecture per result, for this same task. Users can move up and down the task hierarchy in the task detail view, to see architecture-specific as well as cross-architecture comparisons, but this is much easier and more intuitive if the work of permuting tasks is done on the demand for metadata association with the **result**. I'll be adding this as well, this week, at least for choices of hardware architecture, and any other result metadata fields that come up.
