### ISSUE TITLE
Pushing accepted submissions to twitter

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#413]
This could be more long term, but when submissions are accepted we could have an @metriq twitter account tweet out information about the new submission. This way the twitter account could act like a feed for new benchmark updates the drives engagement and traffic to metriq when the tweets are shared etc.

**Comment by willzeng** [comment]
@WrathfulSpatula @vprusso Perhaps this can go on the longer term roadmap?

**Comment by willzeng** [comment]
Of course would be excellent if it gets in before launch

**Comment by WrathfulSpatula** [comment]
This would fit better with the next sprint milestone, and it's also substantial time to implement, as neither Vincent nor I have experience with the Twitter API, as far as I know.

However, we can start addressing issues in the sprint as soon as public beta launch preparation is finished, so we'll come back to this sooner if we finish everything else sooner.

**Comment by nathanshammah** [comment]
I understand this issue is closed as the related #655.
