### ISSUE TITLE
How do determine task, child task, metric

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#420]
As a user, I am extracting two-qubit gate fidelities from a paper on hardware, **submission** reference: https://metriq.info/Submission/85.
From the abstract, I read: 

> "We measure an average two-qubit Clifford fidelity of 97.1±0.2% with randomized benchmarking. We also use interleaved randomized benchmarking to demonstrate the controlled-NOT gate with 96.3±0.7% fidelity, SWAP with 99.3±0.5% fidelity, and a specialized entangling gate that limits spreading of leakage with 93.8±0.7% fidelity." 

I am unsure of how to add the results. I added to the submission the existing **task** "Two-qubit gate fidelity" and then added the **child task** "two-qubit Clifford fidelity", but then wondered if this, or "controlled-NOT gate fidelity" were instead **metric** to which to add **results**. 

Previously, for another submission ([61](https://metriq.info/Submission/61)), I just used "Two-qubit gate fidelity" as task and **CNOT-gate fidelity** as metric. 

By the way, I created as **methods** a **randomized benchmarking** and **interleaved randomized benchmarking** and **silicon quantum dot processor**

**Comment by WrathfulSpatula** [comment]
I think this issue was addressed, but please feel free to reopen, if more help or clarification is needed.
