### ISSUE TITLE
Add option to display result plots on a log scale

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#423]
For some tasks the results span several orders of magnitude. For example:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/5214594/153435681-55aa7669-3e3b-4937-b471-0527061458b4.png">
Here is would be nice to have an option to display the data on a logarithmic scale (or a log-log scale).

**Comment by WrathfulSpatula** [comment]
We need another unitaryHACK issue or two, and this could be a good one.

One acceptable solution would be to add a UI button that switches between linear and logarithmic, but other approaches will be considered based on their merits.

**Comment by cometta** [comment]
added PR https://github.com/unitaryfund/metriq-app/pull/591

**Comment by cometta** [comment]
remember to close the ticket, thank you
