### ISSUE TITLE
Publish Changelog and/or releases

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#426]
It could be nice to keep track of major changes by publishing on Github a changelog. 
 Due to the CD/CI nature of the website, I have no answer of what could be a "release". Maybe these could be monthly ones. The changelog could be more or less automatically generated, see https://github.com/cookpete/auto-changelog.

In Mitiq we have a [`gh-release.yml` file](https://github.com/unitaryfund/mitiq/blob/master/.github/workflows/gh-release.yml) that via Github Actions help automate releases, e.g., the trigger event is the addition of a `tag` named `v.***` to the master branch.

**Comment by WrathfulSpatula** [comment]
We now have auto-generated change logs, for releases. We will continue to release regularly, (so I think we can close this issue).
