### ISSUE TITLE
Improve plots visualization

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#431]
Many examples can be found at https://dataviz.cafe/. 

Example of possible features:
- reactive data points in plots that provide information once on hovers over with the mouse
- resizable or zoomable axes reactive to the user's touch

(This could also include some automatic data pre-processing before generating the plot.)

**Comment by WrathfulSpatula** [comment]
@willzeng also suggested this API, which I really like. I think it might cover multiple bases well, for our purposes, in that we can stack tabbed views for chart, table, and citation:

https://ourworldindata.org/owid-grapher

**Comment by WrathfulSpatula** [comment]
I think we can close this, after adding Chart.js. We'll open other issues for specific points of criticism on elements of the charts.
