### ISSUE TITLE
Server error for incomplete method 

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#436]
A server error closing the submission modal window appears if, when adding a new method to a submission, I do not fill out all.
"Error: could not reach server" (see screenshot below).

<img width="423" alt="Screen Shot 2022-02-15 at 15 14 36" src="https://user-images.githubusercontent.com/14573436/154080228-8a1cbcfa-7baa-407e-972d-fbc32bdaea55.png">

Even if the intended behaviour is for the user to fill out all the options, this is not a useful correct error message. It loses the information put in by the user as it appears after closing the modal window for the new method. 

As a quick partial fix, if all items are mandatory, we could add an asterisk next to them to mark that they are mandatory (with a legend). This could reduce the number of errors in practice.  I will open a separate issue for discussing whether we want this mandatory or not.

**Comment by WrathfulSpatula** [comment]
I'll add a default, here, but my hands are in this UI anyway while I work on adding a method hierarchy, so let me take this issue while I'm at it.

**Comment by WrathfulSpatula** [comment]
This was fixed in #448.
