### ISSUE TITLE
Highlight optional/required fields

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#437]
When creating a new task, method or result/metric, as a user it would be nice to know what fields are mandatory and what not. For example, there are **tasks** without a "Description" but if one submits a **method** without the "Description" field, an error arises. 

I suggest using either the "(optional)" next to optional fields or an asterisk * next to required ones.

**Comment by WrathfulSpatula** [comment]
@vprusso Note that we have `FormFieldValidators` here already, but they should just trigger on pressing "Submit." I'm going to set defaults for method entry, as well, since I'm editing that UI for method hierarchy.

**Comment by WrathfulSpatula** [comment]
This happens to be addressed in PR #480, in the process of addressing issue #438.
