### ISSUE TITLE
Reduce fields in new task/method

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#438]
I suggest to reduce fields that a user is requested to fill out for a new task or method. As a user I am very lazy. I understood that for methods I need to fill out Name, Full Name and Description to be able to make a submission, but to do so, I generally copy-paste the same word in all fields, also because I am unsure of what to put in the description (see #435), i.e. whether I should add comments on the specific device of the submission or more generally about the method. 

My laziness would suggest eliminating the full name option (can we allow one to edit the full name on the Task/method page?) and say that descriptions are optional. However I don't know the implication of this for the system. Maybe full names and descriptions could be shown as optionally to add in the pages of the Method or Task that get created. This adds another (optional) step, but simplifies the task of adding a metric, which requires adding a submission, a task and method first.

**Comment by willzeng** [comment]
+1

**Comment by WrathfulSpatula** [comment]
I'd suggest automatically copying "full name" from "name," if a member doesn't provide one, and making it immediately obvious at a glance that "name" is the only required field. (I fill all three fields out, with different values, but I see your point.) So long as the user can immediately see that all that's required is the name, I think we accomplish the intent of this issue.
