### ISSUE TITLE
Data points not well visible in plots

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#439]
When looking at this task (https://metriq.info/Task/35) I had a hard time at figuring out where the data points where. 

See screenshot below:

<img width="1250" alt="Screen Shot 2022-02-15 at 15 53 38" src="https://user-images.githubusercontent.com/14573436/154087373-a05ce36d-3536-403c-a5dd-774c90c7f35c.png">

Most of the central part of the plot is empty. This is due to the fact that the data is clustered around a minimum and maximum value on the x-axis. As far as I can tell, there are three issues that affect the plot:
- 1. The neutral atom data point is at the far right, with the label going out of the plot space
- 2. The data points are not very bright or visible
- 3. The plot space, besides the rows, is not markedly different from the surrounding (it could be of a different color?).

An idea for 1. could be to generate by default plotted x-limit and y-limit that are greater than the min and max of the data points.

**Comment by WrathfulSpatula** [comment]
By the way, in that demo page link, the connected scatter plot might be amazing for parent task views of child task SOTA trends. Good find, Will. (Hopefully, it's compatible with React.js.)

**Comment by WrathfulSpatula** [comment]
OWID-Grapher is _very_ bespoke to a given database structure that we can't accommodate, unfortunately. However, Chart.js takes all the low-level work out of D3.js, to produce a fairly wide array of pretty charts. It's theoretically less flexible than D3.js, but we don't need the extra configurability, as far as I can tell, and it immediately fixes many aesthetic issues with our axes and labels.

This is just dummy data, but it looks like this, in the tasks view:
![Screenshot from 2022-02-22 14-12-35](https://user-images.githubusercontent.com/2674693/155202773-827809af-d8f7-4c82-b283-04cd067e73e2.png)

**Comment by WrathfulSpatula** [comment]
(Also, Chart.js is MIT License, which is about as good as it gets, for our open source purposes.)

**Comment by willzeng** [comment]
That chart is already looking better, good find. Might be nice to make the labels on the legends a bit larger so that they are legible in screenshots

**Comment by willzeng** [comment]
Is this closed by https://github.com/unitaryfund/metriq-app/pull/456 ?

**Comment by WrathfulSpatula** [comment]
@willzeng It is. We'll track general chart visualization concerns in #431, so let's close this one.
