### ISSUE TITLE
Ground state energy plot missing points?

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#445]
Looking at the ground state energy task https://metriq.info/Task/2 we see:
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/5214594/154134778-c1d1ccf5-fa86-431d-89ce-ecc1b57019e7.png">

However there appear to be many more submitted points?
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/5214594/154134805-b4e13daa-b2f0-451e-a5ad-89838c7283c4.png">

Should they be missing?

**Comment by WrathfulSpatula** [comment]
I think the confusion is that we have 3 data points for H2 energy, (which is the particular metric selected in that chart,) and 2 of them are nearly identically overlaid, in the bottom right corner.
