### ISSUE TITLE
Clean up numeric axes labels

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#446]
Right now the y-axis labels are typically in scientific notation that makes them hard to read.
<img width="97" alt="image" src="https://user-images.githubusercontent.com/5214594/154135016-a671782b-c834-45e0-b9b5-f1a632f95bf2.png">

Could these be reformatted to usually display the raw values and be more readable?

**Comment by WrathfulSpatula** [comment]
@willzeng It is. To repeat, we'll track general chart visualization concerns in #431.
