### ISSUE TITLE
Centering on cards

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#451]
On lots of the cards the text is slightly higher than center, for example:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/5214594/154707506-8c1debae-089b-40c5-b3af-78ba42be35ed.png">

This applies across the site I think. Would be cleaner to have them properly centered.

**Comment by WrathfulSpatula** [comment]
I have a fix for this. If we detect that description text is empty, we drop the description div and change the title class to remove padding. (Browser debug tools let us experiment with directly changing the page DOM, here.) I'll have this shortly, if you could please review @vprusso.
