### ISSUE TITLE
ArXiv Labs and arXiv integrations and APIs

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#457]
As mentioned in #151, it seems that arXiv is undergoing a revived community-oriented API integration. Some recent examples:
- bibtex information for each arXiv submission (on the right of the page, including published paper information)
- Papers with Code integration
- DOI assigned to each new arXiv submission
-  ar5iv, HTML 5 conversion of pdf from latex, https://ar5iv.labs.arxiv.org/, see https://ar5iv.labs.arxiv.org/html/1910.06709

To pull information, Scirate is simply using the bulk api. See this forum https://groups.google.com/forum/#!forum/arxiv-api

This is an open-ended issue for discussion to evaluate what integrations, API could be made and whether the project should reach out to arXiv labs.

**Comment by WrathfulSpatula** [comment]
We've actually started using arXiv API queries, recently! We parse publication dates and authors, in submission detail view.

Thanks for the question/discussion, but we can create a "project" or a milestone in the future, if we need more systematic consideration of arXiv API features to use.
