### ISSUE TITLE
Show labels for all data points

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#462]
Show labels for all data points in charts. See below, where there is a lot of space but only some points display the information on the SOTA data point displays the label. Having labels for all points is more informative (even if the labels show up by hovering over items one by one).
<img width="1155" alt="Screen Shot 2022-02-23 at 17 42 10" src="https://user-images.githubusercontent.com/14573436/155368375-ec78bb1c-adf0-4194-a31b-d8ee2198eb53.png">

**Comment by WrathfulSpatula** [comment]
@willzeng Seemed to be of the opinion that we should specifically only show SOTA data point labels, conversely. (If we have many data points on the graph, ultimately, I think I agree with Will.)

**Comment by WrathfulSpatula** [comment]
Since this issue went stale, we _did_ add labels for all data points. (On mobile, they only appear when clicking data points, due to space limitations.)

If the issue has been addressed, we can close it.
