### ISSUE TITLE
Search yields duplicate results of same submission

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#466]
Searching for a title that is only present as a single submission is sometimes visualized as multiple submissions under search. 

For instance, searching for "Application-Oriented Performance Benchmarks for Quantum Computing" in the search bar yields a result that looks like the following:
<img width="1224" alt="Screen Shot 2022-02-24 at 9 02 50 PM" src="https://user-images.githubusercontent.com/1562214/155639858-02d4aad2-f1fd-4088-aaf8-db5e15e23ab4.png">

Ideally, if there is only one result that corresponds to the search title, it should only be showing that one item.

**Comment by WrathfulSpatula** [comment]
@vprusso I tried searching for the exact submission you gave above, and this bug doesn't reproduce for me. (That is, I see only one copy of the particular submission.) Can you give additional instructions to recreate the bug? Does this still happen? If we can't recreate it, we can also close this.

**Comment by vprusso** [comment]
Seems like this isn't an issue for me as well. I tried on some of the examples that previously generated this behavior. Could have been a complete fluke, but since this behavior appears to be working properly, I'm going to go ahead and close this one.
