### ISSUE TITLE
Sticky footer covers bottom of page 

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#486]
Sticky footer covers bottom of pages. 
<img width="1379" alt="Screen Shot 2022-03-10 at 12 29 35" src="https://user-images.githubusercontent.com/14573436/157653103-485ad341-3c54-4f21-a857-f929c270137e.png">

**Comment by WrathfulSpatula** [comment]
We'll add a spacer at the bottom of the viewport. @vprusso Do you want to take this? In the top level App.js, this can be fixed for the entire app at once, by adding a `<div>` with a fixed height.

**Comment by WrathfulSpatula** [comment]
I need this fixed immediately, so I'm going ahead with it.

**Comment by vprusso** [comment]
> I need this fixed immediately, so I'm going ahead with it.

Sounds good. I'm focusing right now on:
https://github.com/unitaryfund/metriq-app/issues/487
