### ISSUE TITLE
Consider inverting Submission <-> Results in Tasks

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#496]
Consider inverting Submission <-> Results in Task pages. Personally, when inspecting the chart, I tend to want to know more about results, rather than the full list of submissions related to that Task. I propose this order:
- Child Tasks
- Results
- Submissions

(There is a separate issue affecting the upvotes for submissions in Task pages, #487.)

**Comment by WrathfulSpatula** [comment]
This was effectively addressed already, by now! We _do_, in fact, use your suggested order for sections, so we can close this.
