### ISSUE TITLE
Sticky footer a bit invasive

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#497]
The sticky footer is a bit too invasive for my use. Maybe this is just a personal experience. It expands very easily upon hovering there with the mouse. It also springs up very quickly, maybe making that a bit slower would help making it more "calm" to me. Right now I am a bit "concerned" when browsing Metriq not to hover over the bottom of the page with the mouse, to avoid this from popping up. 

Maybe this is just me. Maybe there is an easy fix either by having the footer expanded upon click on an arrow or new text on top "Click for more info", or by reducing the sensitivity of it (make it expand only if hovering over it for many seconds with the mouse?)

Also, when it is compressed, maybe the footer could take up a bit less space, cutting the last empty line from being visualized.

**Comment by WrathfulSpatula** [comment]
A 1/3 second delay has been added. Let me know if this feels like it should be shorter/longer, please.

**Comment by Misty-W** [comment]
It's improved but maybe not quite optimized yet. @nathanshammah, any thoughts?

**Comment by WrathfulSpatula** [comment]
@Misty-W It hasn't been published, yet. :smiley: I'll get it on production, so you can see.

**Comment by WrathfulSpatula** [comment]
@Misty-W It will take a hard refresh of the homepage in your browser, once you're on it, but it's published, now. :+1:

**Comment by Misty-W** [comment]
> @Misty-W It will take a hard refresh of the homepage in your browser, once you're on it, but it's published, now. 👍

Thanks for the quick turnaround Dan, the delay definitely helps! As a future improvement, maybe @francespoblete would have some helpful suggestions on optimizing the formatting to make the footer more compact 😎
