### ISSUE TITLE
API route for metriq submission with specific arXiv link

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#498]
### Task:

Create an API route that accepts an arXiv ID and returns information including (or limited to) a link to the paper in Metriq. If we don't have an entry for it, return the appropriate NOT FOUND HTML status code.

Note that for Metriq submissions that have associated arXiv links, the `arxivID` can be extracted from the `contentUrl` field by extracting the last segment of the URL string. For instance: the content `1911.01927` can be extracted from the arXiv URL `https://arxiv.org/abs/1911.01927`. 

### User Story (User <-> System (REST API) : Success)

This scenario occurs in the event that a Metriq submission with requested arXiv-ID exists

<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">User</th>
    <th class="tg-0pky">System (REST API)</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">1. Call REST API:<br><b>GET /api/v1/arxiv/arxiv_id</b></td>
    <td class="tg-0pky">1.</td>
  </tr>
  <tr>
    <td class="tg-0pky">2. </td>
    <td class="tg-0pky">2. Return <b>HTTP 200</b> with a payload that includes the associated Metriq submission ID.</td>
  <tr>
    <td class="tg-0lax">3. <i>(Received request)</i></td>
    <td class="tg-0lax">3. <i>(Sent request)</i></td>
  </tr>
</tbody>
</table>

### User Story (User <-> System (REST API) : Failure)

This scenario occurs in the event that a Metriq submission with requested arXiv-ID does not exist.
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">User</th>
    <th class="tg-0pky">System (REST API)</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">1. Call REST API:<br><b>GET /api/v1/arxiv/arxiv_id</b></td>
    <td class="tg-0pky">1.</td>
  </tr>
  <tr>
    <td class="tg-0pky">2. </td>
    <td class="tg-0pky">2. Return <b>HTTP 404</b>.                                         
</td>
  <tr>
    <td class="tg-0lax">3. <i>(Received request)</i></td>
    <td class="tg-0lax">3. <i>(Sent request)</i></td>
  </tr>
</tbody>
</table>

**Comment by WrathfulSpatula** [comment]
@vprusso Looks great! I also like the idea of organizing elements of the arXiv API integration under an `/arxiv` prefix.

**Comment by WrathfulSpatula** [comment]
@vprusso Actually, there's one more thing: we're going to version the API, but this is out-of-scope for this issue. However, the route will be `/api/v1/arxiv/arxiv_id`, and we'll semantically increment the version prefix for public consumption, in the sense that any changes to the request or return schema will increment the version prefix, and we'll maintain old versions of the API for long enough to support third-party transition.

**Comment by vprusso** [comment]
@WrathfulSpatula Gotcha, thank you for the feedback!

Regarding the versioning, should we first create an issue that pertains to hooking up these version-dependent API routes are a prerequisite task for this one then? What are your thoughts?

**Comment by WrathfulSpatula** [comment]
The consumer of this route needs only this single route, for now. The versioning is for third-parties. It's overkill to change the entire route structure for this single route, but, if they use any additional routes, we'll talk with them about it, and we'll prefix as appropriate at that point.

**Comment by nathanshammah** [comment]
To begin to address #157, what about providing a reference for `contentUrl`?

**Comment by WrathfulSpatula** [comment]
@nathanshammah We can provide `contentUrl`, if they need it, but the most essential part to know whether the entry is _in Metriq_ is the submission ID, which they could turn around use for the `/api/submission/{:id}` route, to obtain any other information they need. If it makes it simpler for them, we probably actually want to generate a Metriq URL  for the submission, but, given the same `id`, this will always be `https://metriq.info/Submission/{:id}`.

With or without the Metriq link and original source link from this route, they need the submission ID. Also, some flavor of `HTTP NOT FOUND`, like 404, is the correct RESTful response if the resource doesn't exist.

**Comment by WrathfulSpatula** [comment]
@nathanshammah Disregard most of what I said in my email a minute ago: The query parameter _is_ the arXiv ID. They need the Metriq ID, if we have one corresponding. I'll have this done this morning.
