### ISSUE TITLE
Image upload instructions are not clear

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#504]
Uploading image instructions should have clearer instructions. Need to be logged in, need to share direct links, etc.

**Comment by nathanshammah** [comment]
Any update on this? I noticed that also this latest submission by @Misty-W may have had a broken link, likely for the same reason as previous ones. https://metriq.info/Submission/164

**Comment by Misty-W** [comment]
I can see the thumbnail in my submission now that it's approved. I think it's only the thumbnails of submissions under review that aren't showing. @vprusso is that intended behavior for Metriq?

**Comment by vprusso** [comment]
@Misty-W Hmm, intended behavior here would be for thumbnails of submissions both under review and approved to show the proper thumbnail. If this is not the case we should probably open a separate issue for that. I'm happy to do so if that is the behavior you're seeing here @Misty-W

**Comment by Misty-W** [comment]
> @Misty-W Hmm, intended behavior here would be for thumbnails of submissions both under review and approved to show the proper thumbnail. If this is not the case we should probably open a separate issue for that. I'm happy to do so if that is the behavior you're seeing here @Misty-W

@vprusso, yes, let's open a new issue to fix the thumbnails of submissions under review. To clarify my question about whether it was intended, I wondered if you wanted to review submissions first before allowing the thumbnails to be shown.

**Comment by vprusso** [comment]
Actually, you bring up a good point. I would lean on "yes" for wanting to show the image in "Under Review". One such reason for that would be to QA the image and ensure that it displays properly before putting the submission on the main feed page. 

I've opened an issue as you suggested here:
https://github.com/unitaryfund/metriq-app/issues/518

**Comment by vprusso** [comment]
Closing this issue as the thumbnail concern has been addressed in #518 and the instructions for image upload from file hosting below the image link box have been improved since the time of writing this initial issue. Open back up if you disagree, @WrathfulSpatula
