### ISSUE TITLE
Collect optional standard error and sample size on all results

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#505]
One point of feedback we've received in several places is that confidence intervals are critical to fair comparison of results. From the UI/UX perspective, we need to **normalize** the collection and storage of these data in the database. One way to do so is to collect (optional) **standard error** and **sample size** for all results rows. From this information, by the theory of Gaussian statistics, arbitrary confidence intervals can be calculated, in addition to other Gaussian theoretical values. (If your "confidence interval" isn't based upon a sample with Gaussian statistics, by the way, then it fails the necessary assumptions to calculate a true Gaussian confidence interval in the first place, and that needs to be amended before you report your data.)

**Comment by WrathfulSpatula** [comment]
This is part of #452, by the way.

**Comment by crazy4pi314** [comment]
Also https://github.com/unitaryfund/metriq-app/pull/507#issuecomment-1076872786 is relevant here too
