### ISSUE TITLE
Sticky banner partly covers submission button

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#529]
From latest chrome, with default visualization, the sticky banner covers the submission button. As soon as one tries to hit Submit, the sticky footer springs up and completely covers the button. I had to very carefully get close to the button from the top to avoid it and successfully make a submission.

I still think that #497 is not fully addressed and find the footer responsiveness quite irritating as a user (it basically puts me off from making submissions).

 **Maximized window**
<img width="983" alt="Screen Shot 2022-04-27 at 13 14 18" src="https://user-images.githubusercontent.com/14573436/165506654-871e061f-b66e-4747-b3f8-582851707905.png">

 **Not maximized window**
<img width="900" alt="Screen Shot 2022-04-27 at 13 14 03" src="https://user-images.githubusercontent.com/14573436/165506662-7617d113-9860-447c-8507-4067223dd58e.png">

**Comment by nathanshammah** [comment]
I am uploading a screen recording below:
https://user-images.githubusercontent.com/14573436/173639691-2989da82-9488-4043-8045-2640d6b50801.mov

**Comment by WrathfulSpatula** [comment]
Please reopen, if #594 doesn't completely address the issue.
