### ISSUE TITLE
QA CI failing on master branch

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#544]
The action with the deployment to QA is failing on [this](https://github.com/unitaryfund/metriq-app/commit/f7d6499731f7f08b88f47322cb291ba8befae84b) commit, see [here](https://github.com/unitaryfund/metriq-app/runs/6357770586?check_suite_focus=true)
```
Run ssh -i ~/.ssh/id_metriq $SSH_USER@$IP_ADDRESS ./GitHub/metriq-api/metriq-pull.sh
ssh: connect to host *** port 22: Connection timed out
Error: Process completed with exit code 255.
```

**Comment by WrathfulSpatula** [comment]
@nathanshammah @vprusso The deployment pipeline is on `main` branch, and I'm going to go ahead and test it there, since there's no other automatic live deployment, except QA. I'll check and clear any failed logs that expose secrets, (and you should, too,) but I don't expect any such problems.

**Comment by WrathfulSpatula** [comment]
The QA IP address is shown in the logs, but we only discourage users from visiting it, not forbid them. This issue ticket can be closed.
