### ISSUE TITLE
Info about Tasks, Methods, Platforms on submissions

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#547]
I propose to add a little information about Tasks, Methods, Platforms, and possibly Tags on submissions pages, under the lists. We have very specific meanings for these words, which are used for the taxonomy. We provide more details on the Users Guidelines page. The main idea is to help the users understand how to use the platform in an intuitive way and encourage a tidy taxonomy.

- This information could be in small font under each title "Methods", etc. on a submission's page. 
- Links for each item could take one to the User Guidelines (#methods, #platforms, etc. subsections)
- This information could be added actually even next / instead of "There are no associated tags, yet.". 

Thoughts @vprusso @WrathfulSpatula @willzeng ?
Example mockup below:
<img width="1199" alt="submissions-taxonomy-edit" src="https://user-images.githubusercontent.com/14573436/167674794-7237609f-56b0-4b84-8073-9f5744d76d45.png">

Current view:
<img width="1199" alt="submissions-taxonomy" src="https://user-images.githubusercontent.com/14573436/167674825-b254307f-cfd7-4022-b059-579b305384b7.png">

**Comment by WrathfulSpatula** [comment]
This actually looks great, to me! I concur; these brief descriptions would be helpful, without significantly cluttering the UI.

**Comment by vprusso** [comment]
Agreed. I think that's a great idea! It doesn't clutter the UI but has the information at-a-glance. Nice!
