### ISSUE TITLE
Consistent alphabetization for task, method, platform dropdowns

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#550]
Presently, in the submission view if the user wants to add a "task" the tasks displayed in the dropdown appear to be in ascending lexicographical order but the items under the "platforms" dropdown appear to be in another order (perhaps an ordering that is related to when these items were added?)

We should probably have consistent lexicographical orderings in all of these dropdowns for "tasks", "methods", "platforms", and "tags".

**Comment by WrathfulSpatula** [comment]
The fix for platforms is in. This might take a hard browser refresh, on the user end, to update their view code cache, but it's tested and working.
