### ISSUE TITLE
Certain submissions do not allow user to remove tags

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#551]
Consider the following submission:
https://metriq.info/Submission/99

In trying to click on "Edit" -> "Remove" under "Tags", I seem to be presented with the following dialog box. For example, the following submission with existing tags seems to have this problem:
![Screen Shot 2022-05-10 at 2 58 02 PM](https://user-images.githubusercontent.com/1562214/167703743-f7b46e24-44c7-44cf-af77-f91978bc18bd.png)

**Comment by nathanshammah** [comment]
Ah ok see also #552, we filed it at the same time!
