### ISSUE TITLE
Some tags seem duplicates

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#554]
Some tags seem duplicates, I am not sure if there is a space added at the end of either one (and thus technically the difference is correct but we should format the input strings) or it's a classification issue. 
See the examples of `compiler` and `quantum machine learning`– this can be easily reproduced on the tags page using alphabetical ordering:
<img width="1094" alt="Screen Shot 2022-05-10 at 21 19 55" src="https://user-images.githubusercontent.com/14573436/167705895-6314316d-7481-4fc5-8de4-1fe1f766de09.png">
<img width="1118" alt="Screen Shot 2022-05-10 at 17 09 03" src="https://user-images.githubusercontent.com/14573436/167705918-83c3d36c-c4e1-48a0-9924-2471516d0a63.png">

**Comment by WrathfulSpatula** [comment]
In the process of expanding acronym tags, I missed some duplicates. I can combine these, easily.

**Comment by WrathfulSpatula** [comment]
Nathan, thanks for the tip, to scan the list alphabetically. I've done so, and I removed all duplicates I saw. Feel free to close the issue, when you are satisfied.

**Comment by WrathfulSpatula** [comment]
Judging by the alphabetically sorted tags list, I think we can close this.
