### ISSUE TITLE
Sometimes blank page at Metriq.info

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#557]
Sometimes on my browser from PC (latest chrome) I get a blank page when I first reach Metriq.info. If I refresh, it loads the homepage correctly.
<img width="943" alt="metriq-blank-page" src="https://user-images.githubusercontent.com/14573436/167810254-e0ff1b3d-722f-4e70-a543-3cdd7e0a6522.png">

**Comment by vprusso** [comment]
I wonder if perhaps you could try deleting your cookies for metriq? I'm wondering if something that is cached is causing this problem. Would you agree with that approach @WrathfulSpatula ?

**Comment by vprusso** [comment]
Attempted to reproduce on the following browsers with no success:

### System
OS: macOS Big Sur (11.6)

### Browser(s)

Mozilla Firefox: 101.0 (64-bit)
Google Chrome: Version 102.0.5005.61 (Official Build) (x86_64)

Closing for now, but please reopen if this issue persists or occurs again. If so, please respond to this comment with browser details, etc.
