### ISSUE TITLE
Log in prompts to homepage

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#558]
This is a minor UX glitch, but I noticed that if I try to edit something on Metriq and my login has expired for time, I can correctly log in, and then I am prompted to the homepage, not the page I was surfing. To help retain user focus, it could be great if we could store the Submission/ task / ... page the user was on and take the user back once they logged in. 

Additionally, given the position of the mouse in the page by clicking to "Submit" the Log In, it sometimes triggers a continuous scroll of the Metriq homepage.

**Comment by WrathfulSpatula** [comment]
@vprusso Sorry for the crossed wires, but I accidentally grabbed your issue for chart axis ticks. Please take a look at this one, for your next issue. The general concept is called a "return URL," and there's probably one or a number of fairly standard options for doing this with `react-router`, which we use for sitemap navigation.
