### ISSUE TITLE
Removed Method listed with submission counter

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#561]
Some Methods removed from any submission are still listed on the Methods page (ibmq-{devices}, OQC lucy), at https://metriq.info/Methods. they are not deleted if no submission is attached to them and the counter on the Methods page still counts the submission. 

See OQC Lucy, that is listed as a Method with attached submissions and still exists as a page [here](https://metriq.info/Method/91) but then does not have attached submissions any more. I think something does not get updated when one deletes the method (and then, as in this case, updates to Platform, see the [OQC Lucy platform page](https://metriq.info/Platform/10). The relevant submission is [this one](https://metriq.info/Submission/123)).
<img width="1085" alt="metriq-oxford-2" src="https://user-images.githubusercontent.com/14573436/167873537-f6feaf0c-0970-41ac-b2fc-d6e8d7cdefc5.png">
<img width="1072" alt="metriq-oxford" src="https://user-images.githubusercontent.com/14573436/167873557-987334c9-a6d6-4d7c-94fa-4902cbe04fb9.png">

**Comment by WrathfulSpatula** [comment]
I think I can guess where the counting problem with deleted results/submissions is. I'm on this immediately.

**Comment by WrathfulSpatula** [comment]
This took longer than I expected, because there was also a problem with method deletion in general, which I have fixed. Both bug fixes are up, in the PR referenced above.

**Comment by WrathfulSpatula** [comment]
The fix that worked in my local copy does not appear to work on production, so I'm reopening this.
