### ISSUE TITLE
Unauthorized error on submission and my account

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#587]
I get the following errors if I try to make a new Submission or see My submission. The login seems to be successful. See the two snapshots below.

<img width="1380" alt="metriq-unauthorized-my-submissions" src="https://user-images.githubusercontent.com/14573436/171185716-1cc952e5-624d-45c5-847f-2d96f0a08ed4.png">
<img width="888" alt="metriq-unauthorized" src="https://user-images.githubusercontent.com/14573436/171185725-c0d7ad74-b735-4884-ab15-821ee06b1001.png">

**Comment by vprusso** [comment]
Think I beat you to it :) 
https://github.com/unitaryfund/metriq-app/issues/586
