### ISSUE TITLE
Bug: On mobile- Text flowing out of box

### ISSUE THREAD

**Issue by MariaM0003** [unitaryfund/metriq-app#624]
On the "trending" page of Metriq, the text flows outside of its box as shown in the attached screenshot. 
Happens on mobile only. 
![IMG-5275](https://user-images.githubusercontent.com/94807202/177912161-a58c0d6e-5164-4825-8256-6b6e231e0cd4.PNG)

**Comment by WrathfulSpatula** [comment]
This has since been fixed. (Thank you!)
