### ISSUE TITLE
Bug/Enhancement: Stay logged in for longer

### ISSUE THREAD

**Issue by MariaM0003** [unitaryfund/metriq-app#628]
I find that I have to log back into Metriq very often. It would be convenient to stay logged in for a longer period of time.

**Comment by WrathfulSpatula** [comment]
Thanks for the suggestion! Let me explain the logic behind how long users stay logged in:
- The user session expiration time is 30 minutes, but...
- Performing _any_ API call to the back end (which occurs when navigating to almost any page in the app) resets the 30 minute timer.

Given the usage pattern we _tasked_ Maria and Karen with, it makes sense that, even with the user session time window reset, you two might have had to log back in the course of a day of work. However, as we try to balance convenience with security, _most_ common usage patterns probably would not need to log back in a single session of use, while keeping the base time window of the session helps keep accounts secure.

So, I think we'll decline to change this configuration, for now. Please reopen, if you notice anything new.
