### ISSUE TITLE
Image preview doesn't show up

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#630]
Am getting this image preview:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/5214594/178757216-fede6b2b-4f7b-410d-8349-b5075b728c1e.png">

For this image: 
https://ibb.co/P6TxKCd

**EDIT:**

As this appears to be a common mistake users make, could we add some
additional instruction or feature to avoid the problem?

**Comment by willzeng** [comment]
This was fixed by directly linking to the image. Likely to be a common mistake

**Comment by vprusso** [comment]
Combed through the submissions to check if any others are affected by this. From what I can tell it doesn't seem to be the case. For now, I'll close this issue as this seems like a one-off case, but will reopen if this appears more consistently throughout.

**Comment by willzeng** [comment]
As this appears to be a common mistake users make, could we add some
additional instruction or feature to avoid the problem?

**Comment by WrathfulSpatula** [comment]
@vprusso We should prioritize bug issue tickets first. I _also_ added code to the workflow that tries to extract an image URL from _any_ link that is not directly to an image file, but please take a look and assess if we're sufficiently covered this. If we have, go ahead and close the issue. Otherwise, plan and implement how we can fix this.

**Comment by vprusso** [comment]
@WrathfulSpatula that automatic image extraction is slick--works on sites a good chunk of random websites that I tried quite well!

Related, but not our problem, it does seem like [imgbb](https://imgbb.com/) is down (again, at least at the time of this writing). I think @willzeng 's initial comment in this thread arose from the last time that this hosting site was down. As it seems like this goes down quite a bit, I'm wondering if perhaps we want to suggest an alternative image hosting site for users that are free and have more reliable uptime. 

Perhaps something like imgur? Do you think that would be a reasonable replacement suggestion for metriq users, @WrathfulSpatula ?

If agreed, I can close this issue and update the imgbb links to point to imgur (or other) instead.

**Comment by WrathfulSpatula** [comment]
@vprusso It's up to you, if you think it's worth directing people to imgur. (I license you to make the decision, here.) Either close the issue, or update the links and then close it. It's up to you.

**Comment by vprusso** [comment]
imgbb seems to be working again. Perhaps we can reopen if this issue persists, but I'll close for now.
