### ISSUE TITLE
Explicitly tell users where to find saved drafts

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#633]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/5214594/178758731-6ae9e526-a4ef-4d6d-9489-6bf6d5d74657.png">
Could also tell users here that the draft is saved under "My Submissions"

**Comment by KarenRezkalla2** [comment]
We can have a text info bar that the user can see when they hover over the button telling the user where the saved drafts are located.

**Comment by vprusso** [comment]
Nice. I like @KarenRezkalla2 's idea to include popup text for the "Save draft" button. I'll go ahead and get on adding that.
