### ISSUE TITLE
Auto-populate is using data from previous submission

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/metriq-app#634]
<img width="829" alt="Screen Shot 2022-07-13 at 7 29 20 AM" src="https://user-images.githubusercontent.com/82074193/178758862-b70c18a5-8cb7-4182-8656-0c45e361bc57.png">

**Comment by WrathfulSpatula** [comment]
This is controlled by the browser, not by the site code. (That's not a type-ahead field, just an HTML input code.) Sorry to close this unresolved, but there's a perennial tension between how the code is supposed to render according to HTML and other standards and how the browsers want their interfaces to work, and browser interfaces aren't directly up to the web app code.
