### ISSUE TITLE
Bug: Links not working

### ISSUE THREAD

**Issue by MariaM0003** [unitaryfund/metriq-app#635]
On the "User Guidelines" page under "About" : 
The links under the title "About Metriq" do not work. You get a 502 Bad Gateway error when you click the links. 

![Screenshot 2022-07-13 103427](https://user-images.githubusercontent.com/94807202/178760026-012d52a7-dea0-46e9-9bb1-d422df359e02.png)
![Screenshot 2022-07-13 103414](https://user-images.githubusercontent.com/94807202/178760029-db6664b8-89f8-436b-b23e-1e788ba86b17.png)

**Comment by MariaM0003** [comment]
> Hmm. I'm not seeing these 502 errors. They seem to be directing to the proper pages. Can you check again, @MariaM0003 ? Also, are you noticing this behavior as well @WrathfulSpatula ? Seems to be working okay for me.

You're right @vprusso, the links are working now. I don't know why it wasn't working this morning.

**Comment by vprusso** [comment]
Gotcha. Could have been pinging when metriq was temporarily down (as a possibility). I'll go ahead and close this issue now, but please, if you notice the behavior again feel free to open it back up! Nice catch in any case!
