### ISSUE TITLE
Schema seems redundant

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#636]
In submitting a result for algorithmic qubits it looks like this:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/5214594/178760142-48e6391b-b808-4bec-999b-036b5462b4b0.png">

As a user, I feel like I'm putting Algorithmic Qubits in 3 different places when it really is the same thing. 

Perhaps some more guidance is needed for users that they may sometimes end up duplicating?

**Comment by vprusso** [comment]
That's a good point. I'm wondering if it is perhaps a categorization/classification issue on our end where perhaps "Algorithmic Qubits" really only makes sense in one of those three categories? 

If not though, would this extra information be useful to be included on the F.A.Q. page, About page, etc.? Or something else perhaps?
