### ISSUE TITLE
Mobile charts still need work 

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#643]
This looks crowded
![Screenshot_20220721-135702](https://user-images.githubusercontent.com/5214594/180208256-0c8dbbf4-5890-4694-8ed9-6690fbb73701.png)

**Comment by Jay3162** [comment]
Hiya, can I work on this for ya?

**Comment by vprusso** [comment]
By all means--we would welcome your contribution to Metriq, @Jay3162 !

**Comment by nathanshammah** [comment]
This is definitely improved at the moment, i.e., charts take full screen space, are readable, data points can be easily selected. I'd close this issue and allow for more specific suggestions in new issues to be opened.
