### ISSUE TITLE
Clearly mark which items are required in submission flow

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/metriq-app#645]
Sometimes I try to add results (mistakenly) before I've completed the entire form. When doing so I get this modal:
<img width="386" alt="Screen Shot 2022-07-21 at 6 15 53 PM" src="https://user-images.githubusercontent.com/12703123/180263275-a2e34700-3b63-49bf-8a56-92ee643ab0ec.png">

This is great, but without highlighting which field is missing/mistake it is hard to quickly find which field is missing/incorrectly formatted. Would be great to highlight in red, or bold, or even gray out the add results section before it is valid to add them.

**Comment by natestemen** [comment]
I see now that we **do** actually have a warning if the user has entered _something_ into the box, but not if the cursor has not entered the box.
<img width="883" alt="Screen Shot 2022-07-21 at 6 20 41 PM" src="https://user-images.githubusercontent.com/12703123/180264466-1ee056f6-8049-4f8c-a26d-97d3e9dc6af4.png">

**Comment by WrathfulSpatula** [comment]
What we can do instead is also activate the validation red text if the user hits submit.

**Comment by WrathfulSpatula** [comment]
You know, it's a long form: we'll just proactively trigger the validator text to start, in this form.

(In short forms, that tends to make people feel like the UI is "screaming at them" for something they haven't done, before they have any opportunity to read and complete the form; in this case, I think will rather just feel like the form is telling the user more useful information.)
