### ISSUE TITLE
improve README for non-developers

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/metriq-app#647]
We link to this GitHub repo from https://metriq.info, so I would think many people are coming here to learn a bit more about the project. The README is currently great for devs, but not necessarily someone who wants to learn a bit more about the project as a whole. Adding some branding, and a brief description similar to how we do in [mitiq](https://github.com/unitaryfund/mitiq) might be helpful.

**Comment by nathanshammah** [comment]
Great point @natestemen. Would you be up to work on it? It's not a high priority issue but would be a great addition.
