### ISSUE TITLE
Cookie policy

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#661]
In our cookies, we collect only the minimum data necessary to identify a member account login session in order to use the back end REST API securely. However, we need to explicitly explain this to the user, when they first join.

**Comment by vprusso** [comment]
Does it make sense to add this to the `MetriqTermsofUse.html` file? That one looks like a lot of specific legal jargon that I don't want to go putting an arbitrary statement in. It does, however, seem like the most sensible place to put it. Thoughts?

**Comment by WrathfulSpatula** [comment]
@vprusso It's not just a matter of including the legal text; we need to make the user aware and let them opt in. We'll talk about it on Discord, but no, adding to the terms of use is not sufficient, particularly for publicly browsing users who still have cookies. (Our app's cookie is designed not to store or track sensitive data, but we use Google Analytics, for example.)
