### ISSUE TITLE
Spacing is tight on the task page

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/metriq-app#667]
This should have more vertical spacing for the Submission count text:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/5214594/181783538-96418fcc-1e83-4a4a-b0da-ab6f5fde4291.png">

**Comment by WrathfulSpatula** [comment]
This was addressed. Take a look, and let me know if you have more to say on this issue!

**Comment by willzeng** [comment]
Yep this is better!
