### ISSUE TITLE
LaTeX/MathJax rendering is incomplete

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#671]
I mobile, I see LaTeX rendered correctly. However, (on Ubuntu 22.04 FireFox,) I do not see it on desktop. Fix LaTeX rendering for desktop.

**Comment by vprusso** [comment]
Bumping this one up based on the community call today. It seems as if MathJax rendering is not properly displaying on Linux/Mac boxes. The way in which MathJax is being used in our case is most likely outdated and needs to be updated. 

Tagging @natestemen and @WrathfulSpatula from our discussion.

**Comment by WrathfulSpatula** [comment]
Fixed by 1f82744!
