### ISSUE TITLE
My Submissions page opens to the trending submissions page

### ISSUE THREAD

**Issue by MariaM0003** [unitaryfund/metriq-app#672]
I'm not sure if this is just a bug on my end, but after logging in when I press My Submissions, it takes me to this page, https://metriq.info/Submissions/Trending.

**Comment by WrathfulSpatula** [comment]
I've confirmed the bug. I know how to fix it, but I'll give you the option of attempting it, if you want, as the one who opened the ticket, @MariaM0003.

**Comment by MariaM0003** [comment]
I’d like to attempt it.

**Comment by MariaM0003** [comment]
https://github.com/unitaryfund/metriq-app/pull/674
