### ISSUE TITLE
Font size & alignment varies a lot from mobile

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#686]
Font size range widely, especially from mobile, on a submission page:
![metriq-mobile-ux](https://user-images.githubusercontent.com/14573436/188166833-3764824e-4e07-4b08-8706-0806122093e5.jpg)
This may be partly related to #660.
Can you please:
- reduce a bit the size of the "Methods", etc. titles
- Clump more neatly together the content under each category, which now seems too close to the next category title. For example, "compilation", which is under "Tasks", is very close to "Methods". 

About alignment:
- The "Edit" text is not in line with the titles on the left
- The social icons for Twitter and Facebook are much smaller than the other icons. Maybe it's fine as it is, but it seemed a bit strange when they are lined up next to the others.

**Comment by WrathfulSpatula** [comment]
@vprusso I almost have this done. I woke up today, and I just wanted to knock off a bunch of styling issues, (if they're an eyesore and I need low-planning tasks to keep me busy on a Monday).

**Comment by WrathfulSpatula** [comment]
@nathanshammah Please take a look at production and let me know if I missed anything, here. I know that the "Edit" button doesn't align with (only) the title, but it _does_ align vertically centered relative the block element of title-with-description, which I personally think looks better, at least by now.
