### ISSUE TITLE
Bug: Draft status not reflected on user submission page

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#698]
Filtering on draft status does not appear to be working on user pages i.e.:
https://metriq.info/User/40/Submissions

Tagging @natestemen and @WrathfulSpatula for further commentary from our discussion for this issue.

**Comment by natestemen** [comment]
I also noticed that my submission from last week (https://metriq.info/Submission/275) does not show up in my list of submissions (https://metriq.info/User/40/Submissions).

**Comment by WrathfulSpatula** [comment]
Fixed by d6b74a3!
