### ISSUE TITLE
Submission link in header points to tasks instead of submissions

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#699]
Link that this points to should redirect to proper location (submission instead of tasks).

**Comment by natestemen** [comment]
Just to clarify, it is the "submissions" link in this part of the header:
<img width="953" alt="Screen Shot 2022-09-30 at 7 44 32 AM" src="https://user-images.githubusercontent.com/12703123/193295562-41e1635c-8682-443f-aab0-9df9be493964.png">

**Comment by WrathfulSpatula** [comment]
Fixed by ae6b1c7!
