### ISSUE TITLE
Allow user to upload results to Metriq from file

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/metriq-app#706]
As a user, it's inconvenient to copy and paste data points individually from a file when adding results to Metriq.

**Comment by WrathfulSpatula** [comment]
We can include a bulk upload from CSV. This might take some forethought and a user story, as for a design, but it would be extremely useful.

**Comment by WrathfulSpatula** [comment]
@Misty-W Is there a chance that what Vincent is doing with the Python client app, for his benchmark pipeline, is a solution that serves your need too, in this issue? Or would web-based bulk upload from CSV be a valuable feature to you, regardless? (It is a significant amount of work to implement, and it doesn't solve the problem of users entering improperly-formatted data, without additional implementation on top of that, but the important point is that we serve this user need in _some_ way that makes it comparatively friction-less.)

**Comment by Misty-W** [comment]
I'd like to take a look at the Python client first. It's been awhile but I think this issue arose from a jam session where we were copy and pasting data one-by-one from a spreadsheet.

**Comment by nathanshammah** [comment]
I think this is now addressed, @vprusso?

**Comment by vprusso** [comment]
Yes, I think the client handles this. Will close!
