### ISSUE TITLE
New Submission button on submission page?

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/metriq-app#714]
As an infrequent user of Metriq, I don't always remember what buttons I need to use to start a new submission. My first reaction is to click on "submissions" which brings me to this page:
<img width="770" alt="Screen Shot 2022-10-21 at 7 09 49 AM" src="https://user-images.githubusercontent.com/12703123/197215973-66981113-37e1-4de6-8f16-01a84bfa9a82.png">

Wondering if we should add an additional button on this page that's closer to the center (maybe some shade of green) to get the users attention? WDYT?

**Comment by WrathfulSpatula** [comment]
In general, I might agree in other apps. However, there is literally _always_ a large "Submit" button, on every view, in the upper right corner. I realize some users will forget that it's there, but the redundancy might be more confusing than helpful.

If anyone disagrees, we'll reopen the issue, but I think this is "overkill."
