### ISSUE TITLE
New user could not register

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#724]
A new user (@vtomole) could not register last Friday. Initially they did not add some required field information, but could not register. @WrathfulSpatula can you look if you can reproduce the issue and understand if it is a general one or some glitch occurred for @vtomole? Could it be that he already registered (my guess)?

**Comment by WrathfulSpatula** [comment]
@nathanshammah I just tested the registration flow: so long as the user gives a _unique_ user name and a _unique_ email, with a valid password and password confirmation, and clicks the  button to indicate that they accept the T&Cs for the app, I can register.

The point of failure is likely to be one of these:
1. Username was not supplied or is not unique
2. Email was not supplied or is not unique
3. Password wasn't supplied or didn't match the confirmation field
4. The button wasn't clicked to indicate acceptance of the terms.

The workflow seems to be functioning and validating correctly. If Victory is still having trouble signing up, maybe it would help for him to tell us the error message he receives, or please give us a screenshot?

**Comment by vtomole** [comment]
There was no error message. The sign up button refused to click. Maybe i've already signed up before; that's why it's refusing. Would be good to see a "username/email is already taken" error message if that's the case.

**Comment by WrathfulSpatula** [comment]
@vtomole I'm sorry if the form wasn't clear, but the registration front end doesn't make an API call to the back end until the button is clicked, so it won't block you from hitting the "Submit" button if you enter a username or email that's already in use. (I just checked.) However, the red-font validation messages should indicate what's failing about front-end form validation that's preventing you from clicking "Submit." By the way, I just looked at the database, and I don't recognize your name or email within the users table, but maybe I missed it.

Are you sure you clicked the checkbox that indicates that you accept the terms and conditions? It should also tell you in red font if username, email, password, or password confirmation aren't valid. In theory, if there are no invalid fields, the same logic that clears all the respective validator messages should also enable the "Submit" button.

**Comment by vtomole** [comment]
I have an account now. Maybe the form just didn't tell me that my account was created?

**Comment by WrathfulSpatula** [comment]
I wish I knew what the issue had been! Looking at the database, you just created the account now, since the last time I looked at the users table, but we failed to communicate something, in the design of the form validation. I'm not sure what it was, but I'm glad you have an account, now!
