### ISSUE TITLE
Fix CI (remove QA publishing pipeline)

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#725]
Add CI test for user registration and login. Maybe this could be a github action that registers a new user, logs in, and then deletes the user recurrently?

**Comment by WrathfulSpatula** [comment]
We already have such a test in our unit tests, actually. The reason for the CI failures on `main` branch is that we longer publish to the QA environment, for now. However, I can disable the publishing pipeline.

**Comment by WrathfulSpatula** [comment]
@nathanshammah For reference, the unit tests are in the **back end** API; we test the registration **routes**, but testing the **web user interface** is more difficult and less common in practice, if we wanted to simulate user inputs based upon typing and button clicks, for example.
