### ISSUE TITLE
Cannot create new method in add submission view

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/metriq-app#735]
When attempting to add a new method in the "Add Submission" view via the "New" method modal, the "Submit" button in the modal is greyed out and one is not able to create a new method.

**Comment by WrathfulSpatula** [comment]
You need to select a specific method in the autocompletion text field dropdown, Vincent. Once you change the text again, the "Submit" button _should_ be greyed out. The point is to only allow reuse of existing methods unless a new one is specifically being created.
