### ISSUE TITLE
Display arXiv number of data points in chart

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#744]
It would be great to provide an option to display the arXiv number related to a given submission of a data points in a chart relative to a metric. See the mock up below. This could be enabled by a toggle button so that the user can opt in to have this feature. 

This would make the chart even more significant for screenshots to include in research-related slides for scientific talks in my opinion.

Practically, this could check if the provided link is in the format of an arXiv link (e.g., https://arxiv.org/abs/2210.07194), and render it in a short format on the chart, e.g., arXiv:2210.07194 or just 2210.07194 with arXiv written just on the button outside the chart drawing space.
<img width="1076" alt="metriq-arxiv-chart" src="https://user-images.githubusercontent.com/14573436/203322752-9d663663-7725-4038-a7e9-9613f5b86197.png">

**Comment by WrathfulSpatula** [comment]
Upon discussion with Nathan, we can't roll this out as-is, because its illegible on many charts, but there's recourse:
1. Only display it for SOTA
2. Give an option to toggle arXiv ID or method label, on SOTA.
