### ISSUE TITLE
Divide top-level tasks from rest

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#747]
Right now, when making a new submission, the top level tasks (Applications, Hardware, Error correction and mitigation, Simulation, Compilation) are listed alphabetically in the drop-down list that has recently updated to allow for text input from the user to enable filter search on existing tasks. This way though their different role in the platform is hidden. 

<img width="822" alt="metriq-task-taxonomy" src="https://user-images.githubusercontent.com/14573436/203325938-163c20a9-4f8a-4793-b743-affe39bce0c4.png">

I wonder if we want to make their role evident by creating an extra top-level task section where users can simply tick (multiple select) where they belong to.

Additionally based on this condition, also filter results showing only the results of lower-level tasks that fit under a top-level task. 

Alternatively, top-level tasks could be automatically added explicitly if the chosen task belongs to a given top level task. For example, I choose ZNE, and QEC/QEM is added automatically.

**Comment by WrathfulSpatula** [comment]
If the purpose of making a (taxonomic) "submission" is to show "results" of "methods" against "tasks" on "platforms," I'm not sure that we need to allow top-level task selection in this section _at all_, as top-level tasks _don't_ show results, ever.

What do you think about allowing top-level task selection _only_ as a "parent task," but not as a submission foreign key reference, (i.e. attached to the submission as the user sees it)?

**Comment by nathanshammah** [comment]
Pinging @willzeng because I do not have a preference (but understood they may have had a suggestion). Main focus should be to solidify existing tasks and related taxonomy to avoid duplication.

**Comment by willzeng** [comment]
What @WrathfulSpatula suggests makes sense to me. Let's do that!
