### ISSUE TITLE
Exported results data with .csv extension

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#770]
Right now, results are exported as a `.txt` file when clicking on the "Export to CSV" button. 
The structure of the text file for quantum volume page is [this one](https://metriq.info/Task/34), which seems csv format, but I guess that we could have it as `.csv` file.
```
"key","name","submissionId","platformName","methodName","metricName","metricValue","qubitCount","circuitDepth","tableDate"
348,"Validating quantum computers using randomized model circuits",42,"ibmq-tokyo","Heavy bitstring sampling","Log Quantum Volume",4,,,"10/11/2019"
349,"A quantum-classical cloud platform optimized for variational hybrid algorithms",44,"Rigetti Aspen-4","Rigetti Aspen-4","Log Quantum Volume",3,,,"5/31/2020"
``` 
etc.

**Comment by vprusso** [comment]
Thanks, Nathan. I'm going to add this to our milestone for improved user design.
