### ISSUE TITLE
Increase a little bit font size of labels

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#775]
If I take a screenshot of the Metriq charts and post it on social media, the labels are too small to be read. It would be great to make them a littlebit bigger in font. Maybe enforcing a multiline wrapping could limit the horizontal size and keep them compact with that respect. Paperswithcode has small font too but still a bit bigger, I provide some snapshots below. 

<img width="1197" alt="papers with code cifar-1o" src="https://user-images.githubusercontent.com/14573436/216419560-0ee4f39b-6861-46b3-93fb-f27a9ee67f62.png">

<img width="1391" alt="Screen Shot 2023-01-24 at 16 44 45" src="https://user-images.githubusercontent.com/14573436/216419409-ac2848ea-23b2-4864-b3f4-5e2df1b74daf.png">
eed6f9.png">
<img width="450" alt="Screen Shot 2023-01-24 at 16 42 55" src="https://user-images.githubusercontent.com/14573436/216419274-653c7a9a-6c6c-434c-861f-f840a4f6adf3.png">

**Comment by WrathfulSpatula** [comment]
It's also the contrast. In addition to increasing the font size a point or two, I'll back off the grayscale on the site theme. (#FFFFFF hard white isn't what we want, but closer.)

**Comment by WrathfulSpatula** [comment]
Posting for my own reference, as well as a preview to others:
![image](https://user-images.githubusercontent.com/2674693/217942995-052c838c-89d4-4ec1-b026-e78dbf2d82fb.png)

**Comment by WrathfulSpatula** [comment]
I think this is what I'm going with:
![image](https://user-images.githubusercontent.com/2674693/217945084-e40f8a86-8837-4d5b-a1f0-93914d5661c6.png)
