### ISSUE TITLE
General search bar

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#786]
We've had several requests for a site-wide search or filter bar. At least, as we have the filter bar per taxonomy category, we could combine all taxonomy categories into a site-wide filter bar.

**Comment by nathanshammah** [comment]
Upvoting this as today I experienced how this would have been useful for me, as I was looking for some GKP state results which I wanted to check if were present in Metriq.

**Comment by WrathfulSpatula** [comment]
Here's the design: it's just a filter on the union of all taxonomy "searches," (which are really rather "filters"). It will be in the app header section, alongside the navigation menu.
