### ISSUE TITLE
Unable to access site

### ISSUE THREAD

**Issue by 1ethanhansen** [unitaryfund/metriq-app#844]
I've tried accessing from Brave (chromium-based) and Firefox, both give this error:

```
This site can’t provide a secure connection
metriq.info sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

If I'm the only person having issues, go ahead and close this. Otherwise, I thought opening an issue to track it would be good

**Comment by WrathfulSpatula** [comment]
Sorry about this! The DNS registration wasn't set to auto-renew, and, of course, the expiration date hits in the middle of a long holiday weekend!

The site should be back online, now. There might be a DNS propagation delay, but it's transient, and I can already access the site again in NJ, USA.

Please reopen the ticket if you're still having issues after DNS propagation. (See https://www.whatsmydns.net/#A/metriq.info, and the IP should be 3.14.43.53.)

**Comment by 1ethanhansen** [comment]
Perfect, it's back! Thanks!
