### ISSUE TITLE
Click on chart data point takes to other submission

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#856]
Clicking on the data point associated with the ETH Z paper on the chart at https://metriq.info/task/141 takes one to the google Sycamore submission.

<img width="1046" alt="Screen Shot 2023-06-16 at 16 32 22" src="https://github.com/unitaryfund/metriq-app/assets/14573436/e1eab169-212f-44b4-8b23-98875db0b13d">

**Comment by WrathfulSpatula** [comment]
Bit of housekeeping: this was already addressed. Please reopen the issue, if it recurs.
