### ISSUE TITLE
Some problems with password recovery

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/metriq-app#867]
I noticed two strange things when trying to recover my password:

- I tried to recover my password with my personal email. I got a "Could not reach server " error.
- I tried with the unitary fund email address and I didn't get the error. However, I didn't receive the recovery email.

**Comment by WrathfulSpatula** [comment]
It's likely that the support email account has been automatically restricted against certain types of app access. (This has happened in the past.) Let me check on the status of the support account, check the server environment, and update as necessary.

**Comment by WrathfulSpatula** [comment]
@andreamari I've identified that this is exactly the issue. I'll have a fix today.

**Comment by WrathfulSpatula** [comment]
Should be fixed. Please reopen the ticket, if you still notice any issues.
