### ISSUE TITLE
Update 'Add platform' modal on Submissions pages

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#868]
On each submission page the 'Add platform' modal contains the old taxonomy (screenshot below). We should update it with the new fields (architecture, provider, device).

 
<img width="826" alt="old-platform-modal" src="https://github.com/unitaryfund/metriq-app/assets/14573436/573ef8a5-5e16-4edb-8286-81eb92048e25">

**Comment by nathanshammah** [comment]
Just a ping @WrathfulSpatula @vprusso that this still needs to be updated.

**Comment by WrathfulSpatula** [comment]
This has been addressed. (Please reopen if necessary.)
