### ISSUE TITLE
Allow sorting of result items by category

### ISSUE THREAD

**Issue by karlaspuldaro** [unitaryfund/metriq-app#873]
It would be useful to add a feature that allows sorting of result item columns. Here is an example:
![image](https://github.com/unitaryfund/metriq-app/assets/25207344/6ec16bed-0ee0-4bb6-97bd-23298906657c)

**Comment by WrathfulSpatula** [comment]
@karlaspuldaro The column headings actually _do_ sort, if you click them. However, many people have failed to notice this, by now. I think that means we need a visual indicator, that the table can sort.
