### ISSUE TITLE
Text formatting/positioning of buttons on Quantum volume QED-C benchmarks page

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/metriq-app#877]
Text formatting/positioning of "Export to CSV" and "Download to..." buttons of [Quantum volume QED-C benchmarks](https://metriq.info/QEDC) needs cleanup.

See screenshot:

![image](https://github.com/unitaryfund/metriq-app/assets/82074193/18439470-7abd-4671-87d4-ad61ed727c78)

**Comment by Misty-W** [comment]
hi @WrathfulSpatula thanks for looking into this! 
Yes on Chrome and Safari I still see the text running off the buttons. It can probably be inferred that it's supposed to say "download to CSV", but the file format is cut off from the "Export to" button, which could be confusing.  
Is smaller text a viable option?

**Comment by WrathfulSpatula** [comment]
Misty, simplest and least invasive solution seems nonetheless, by now, to adjust the column increments (for smaller screens and windowed views) by 1. Thanks for raising it to my attention! It'll be on production, today.
