### ISSUE TITLE
Include markdown rendering on homepage

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#878]
Include markdown rendering on homepage (this works correctly on the [task page](https://metriq.info/Task/34))

<img width="703" alt="metriq-homepage" src="https://github.com/unitaryfund/metriq-app/assets/14573436/bb3cd166-d0fd-4fb0-9eeb-7fd68afc5929">

**Comment by vprusso** [comment]
Hi @rochisha0

Thank you for your interest in this issue! 

The general issue here is that any text elements surrounded by the `$` delimiters should be rendered as LaTeX but not as expected (as shown in the screenshot from the original issue post). 

The idea would be to determine why this formatting is not appropriately applied in this case and propose a solution that renders these elements as expected. 

Does this make sense? Don't hesitate to let us know if you have further questions and happy hacking!

**Comment by ljcamargo** [comment]
sent a pull request for this: https://github.com/unitaryfund/metriq-app/pull/915

**Comment by WrathfulSpatula** [comment]
Thank you!
