### ISSUE TITLE
Prepopulate result dates in "Add Submission" workflow

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/metriq-app#880]
If a submission URL is from arXiv, then we prepopulate result dates in the "detail view"; we should also do so in the "Add Submission" workflow.

**Comment by AnsahMohammad** [comment]
Can I work on this issue?

**Comment by vprusso** [comment]
Yes, you are free to work on the issue. Once you are able to put forth a diff with solution, we can assign the issue to you.

**Comment by WrathfulSpatula** [comment]
@WingCode Please comment so I can assign you for the bounty.

**Comment by WingCode** [comment]
Commenting..
