### ISSUE TITLE
Group or sort results by task

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/metriq-app#889]
It would be helpful to see the results pertaining to a certain task all together in the list view.

**Comment by WrathfulSpatula** [comment]
I would have expected that the results table could already sort by tasks, methods, and platforms, but this feature was broken! I have a fix, and it'll be on production later today. (I understand that it might not be obvious in the first place that the table sorts when pressing the column heading, but we can cover that in a separate issue ticket, if it remains a secondary issue.)
